# ACTUATOR DYNO CONFIG

# --- 1. SENSOR CONFIGURATION ---
# All logical sensors go here. Port mapping handles the hardware routing.
sensors:
  # --- Reserved (System Functional) ---
  load_torque:
    port: RESERVED_ADC_2
    fs_v: 5
    fs_pos: 500
    offset: 0
    supply: NA  # Internal wiring has permanent power

# --- 3. PHYSICAL PANEL WIRING HARNESS ---
# This maps the physical labels on your dyno's front panel to the internal EtherCAT hardware.
panel_ports:
  RESERVED_ADC_1:
    signal_module: ADC
    signal_channel: ch1
  RESERVED_ADC_2:
    signal_module: ADC
    signal_channel: ch2

# Properties of each device can be accessed via their name in python. i.e. self.devices['input_motor'].torque
# Names provide a way to identify multiple copies of one device
expected_slave_layout: # This section captures parameters required to initialize the classes that wrap ethercat modules
  - { model: EK1100, name: coupler}
  - { model: EL2002, name: digital_output}
  - { model: EL1002, name: digital_input}
  - { model: ELM3002, name: ADC}
  - model: AKD
    name: input_motor
    params:
      flip_torque_sign: False
      gear_ratio: 31 # approximate, used for feed forward torque commands / safeties
      motor_params: #Peaks refer to motor peak, irregardless of drive limits, All currents are in A_rms
        kt: 0.733 # measured torque constant
        k_tanh: 0.022 # defines tanh saturation curve along with kt
      motor_limits: # commands that exceed this value are clipped as they go out to the motor
        torque: 10 # Nm, abs(commands) > limit, are clipped
        velocity: 350 # rad/s, abs(commands) > limit, are clipped
        acceleration: 400 #Rad/s^2
        rotatum: 40 #Nm/s, 4 x peak torque value
      drive_params:
        i_cont: 5.812 # This value needs to match the servo drive setting. torque ff comands are sent to the drive as current commands in units of i_cont / 1000
  - model: AKD
    name: LOAD
    params:
      flip_torque_sign: True
      gear_ratio: 1 #Output should always be set to 1
      motor_params: #Peaks refer to motor peak, irregardless of drive limits, All currents are in A_rms
        kt: 11.7
        k_tanh: 0.016
      motor_limits:
        torque: 330
        velocity: 12
        acceleration: 12 #Rad/s^2
        rotatum: 1320 #Nm/s, 4 x peak torque value
      drive_params:
        i_cont: 12 
  - model: AXON
    name: DUT
    params:
      gear_ratio: 1
      esi_file_name: dyno-debug-esi-extra-filters.xml
      motor_limits:
        torque: 30
        velocity: 6


safeties: # Measured values over these limits will cause the test to stop
  output_torque: 375 # Nm on the output torque cell. measured abs(torque) over this limit will stop a test
  input_torque: 15 # Nm on the input torque cell. measured abs(torque) over this limit will stop a test
  output_velocity: 15 # rad/s on the output. measured abs(velocity) over this limit will stop the test
  input_velocity: 500 # rad/s

gui_params: # defines length and resolution of the plots
  window_length_s: 30
  displayed_samples: 2048

log_keys:
  - [time, time]
  - [dut_mode, devices.DUT.servo_drive_mode]
  - [dut_torque_command, devices.DUT.torque_command]
  - [dut_velocity_command, devices.DUT.velocity_command]
  - [dut_position_command, devices.DUT.position_command]
  - [dut_output_position, devices.DUT.position]
  - [dut_aps_pos_fxp, devices.DUT.aps_position_fixed_point]
  - [dut_input_position, devices.DUT.inc_position]
  - [dut_motor_position, devices.DUT.motor_position]
  - [dut_velocity, devices.DUT.velocity]
  - [dut_current, devices.DUT.current]
  - [dut_effort, devices.DUT.effort]
  - [dut_kp, devices.DUT.kp]
  - [dut_kd, devices.DUT.kd]  
  - [load_mode, devices.LOAD.servo_drive_mode]
  - [load_torque_command, devices.LOAD.torque_command]
  - [load_velocity_command, devices.LOAD.velocity_command]
  - [load_position_command, devices.LOAD.position_command]
  - [load_position, devices.LOAD.position]
  - [load_velocity, devices.LOAD.velocity]
  - [load_current, devices.LOAD.current]